/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author omar1
 */
import AppPackage.AnimationClass;
import javax.swing.JOptionPane;
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public frmInicio() {
        initComponents();   
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel59 = new javax.swing.JLabel();
        lblagregar = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblcambio = new javax.swing.JLabel();
        lblventas = new javax.swing.JLabel();
        lblpagar = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblRegresarPedido = new javax.swing.JLabel();
        lblregresarAlMenu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jSpinner15 = new javax.swing.JSpinner();
        jSpinner16 = new javax.swing.JSpinner();
        jSpinner17 = new javax.swing.JSpinner();
        jSpinner18 = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblregresarAlMenu1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblregresarAlMenu2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jFrame4 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jCheckBox3 = new javax.swing.JCheckBox();
        lblregresarAlMenu3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ingreso = new javax.swing.JPanel();
        lblme = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JPanel();
        lblmenu = new javax.swing.JLabel();
        lblAmpliar = new javax.swing.JLabel();
        lblFinalizaOrden = new javax.swing.JLabel();
        lblAdministrarProductor = new javax.swing.JLabel();
        lblConcultarVentas = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblcalculadora = new javax.swing.JLabel();
        ingreso1 = new javax.swing.JPanel();
        lblcalculadora1 = new javax.swing.JLabel();

        jFrame1.setUndecorated(true);
        jFrame1.setResizable(false);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(232, 167, 53));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(226, 196, 153));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "2xCARNE   $5.00", "3xCUBA LIBRE $3.00", "2xGELATINAS  $1.00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, 210));

        jLabel59.setText("ORDEN ACTUAL");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lblagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Next_page_64px_1 - copia.png"))); // NOI18N
        lblagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblagregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblagregarMouseMoved(evt);
            }
        });
        jPanel1.add(lblagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel64.setText("TOTAL :");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel65.setText("$21.00");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anillo (32 x 32).jpg"))); // NOI18N
        lblAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, -1, -1));

        lblcambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/notas (32 x 32).jpg"))); // NOI18N
        lblcambio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblcambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, -1, -1));

        lblventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bars-chart (32 x 32).jpg"))); // NOI18N
        lblventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 200, -1, -1));

        lblpagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/invoice (32 x 32).jpg"))); // NOI18N
        lblpagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 160, -1, -1));

        jLabel22.setText("NUMERO DE ORDEN :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel23.setText("1");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        lblRegresarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Next_page_64px_1.png"))); // NOI18N
        lblRegresarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegresarPedido.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRegresarPedidoMouseMoved(evt);
            }
        });
        jPanel1.add(lblRegresarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 60, -1));

        lblregresarAlMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/atras.png"))); // NOI18N
        lblregresarAlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregresarAlMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblregresarAlMenuMouseMoved(evt);
            }
        });
        lblregresarAlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregresarAlMenuMouseClicked(evt);
            }
        });
        jPanel1.add(lblregresarAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 280, 510));

        jPanel4.setBackground(new java.awt.Color(226, 196, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(226, 196, 153));

        jPanel7.setBackground(new java.awt.Color(226, 196, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cortesdecarne (150 x 113).png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 100));

        jLabel5.setText("PLATO DE CARNE $5.00");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 20));
        jPanel7.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 50, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pOpera.jpg"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 120));
        jPanel7.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 50, -1));

        jLabel10.setText("PURE DE PAPA $3.00");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pSiciliana.jpg"))); // NOI18N
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));
        jPanel7.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 50, -1));

        jLabel28.setText("LASAÑA  $5.00");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/images2 (150 x 113).jpg"))); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel30.setText("SOPA  $3.00");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 20));
        jPanel7.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 50, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/0343-bocata-de-pollo-asado-con-guacamole-xl-416x236x80xX (150 x 113).jpg"))); // NOI18N
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/85e1595251e8d58308db168e689a0f28db17f9eb_r900_480_2 (150 x 113).jpg"))); // NOI18N
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel33.setText("SANDWICH $4.00");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, 20));

        jLabel34.setText("POLLA    $5.00");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, 20));
        jPanel7.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 40, -1));
        jPanel7.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 50, -1));

        jTabbedPane1.addTab("COMIDA", new javax.swing.ImageIcon(getClass().getResource("/Img/cubiertos (32 x 32).jpg")), jPanel7); // NOI18N

        jPanel9.setBackground(new java.awt.Color(226, 196, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/10postresconlechecondensada (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gelatina-de-navidad (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/images (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/images4 (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/istock89179523small (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/soyfler- (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel53.setText("VOLCAN DE CHOCOLATE $3.00");
        jPanel9.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 130, 20));

        jLabel54.setText("PIE DE LIMON $2.00");
        jPanel9.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 20));

        jLabel55.setText("GELATINAS  $1.00");
        jPanel9.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 90, 20));

        jLabel56.setText("PASTEL DE CHOCOLATE $2.00");
        jPanel9.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 160, 20));

        jLabel57.setText("PIE DE FRUTAS $2.50");
        jPanel9.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 110, 20));

        jLabel58.setText("FLAN DE FRESAS $1.00");
        jPanel9.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 120, 20));
        jPanel9.add(jSpinner13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 50, -1));
        jPanel9.add(jSpinner14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 50, -1));
        jPanel9.add(jSpinner15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 50, -1));
        jPanel9.add(jSpinner16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 50, -1));
        jPanel9.add(jSpinner17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 50, -1));
        jPanel9.add(jSpinner18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 50, -1));

        jTabbedPane1.addTab("POSTRES", new javax.swing.ImageIcon(getClass().getResource("/Img/depositphotos_140707304-stock-illustration-chocolate-ice-cream-icon-in (32 x 32).jpg")), jPanel9); // NOI18N

        jPanel8.setBackground(new java.awt.Color(226, 196, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agua_opt.png"))); // NOI18N
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 110));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/index (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cafe (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cafe(150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dt.common.streams.StreamServer.cls (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mandarina---naranja (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jLabel41.setText("AGUA  $0.25");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        jLabel42.setText("CEBEZA  $2.00");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 20));

        jLabel43.setText("CAPICHINO  $1.50");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 20));

        jLabel44.setText("CAFE  $1.00");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 20));

        jLabel45.setText("CUBA LIBRE  $3.00");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, 20));

        jLabel46.setText("JUGO  $1.50");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, 20));
        jPanel8.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 40, -1));
        jPanel8.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 190, 40, -1));
        jPanel8.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 40, -1));
        jPanel8.add(jSpinner10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 40, -1));
        jPanel8.add(jSpinner11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 40, -1));
        jPanel8.add(jSpinner12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 40, -1));

        jTabbedPane1.addTab("BEBIDA", new javax.swing.ImageIcon(getClass().getResource("/Img/images (32 x 32).jpg")), jPanel8); // NOI18N

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 760, 510));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Comida");

        jFrame1.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 760, 510));

        jPanel3.setBackground(new java.awt.Color(140, 0, 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 40, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jFrame1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        jFrame2.setUndecorated(true);
        jFrame2.setResizable(false);
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(226, 196, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel2.setText("NUMERO DE ORDEN ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 20));

        jTable1.setBackground(new java.awt.Color(226, 196, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", "AGUA", "$0.50"},
                {"1", "POLLO", "$5.00"},
                {"2", "CARNE", "$5.00"},
                {"3 ", "CUBA LIBRE", "$3.00"}
            },
            new String [] {
                "CANTIDAD", "PRODUCTO", "PRECIO"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 460, 90));

        jButton1.setText("CAMBIAR ");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jButton2.setText("AGREGAR");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        lblregresarAlMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/atras.png"))); // NOI18N
        lblregresarAlMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregresarAlMenu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblregresarAlMenu1MouseMoved(evt);
            }
        });
        lblregresarAlMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregresarAlMenu1MouseClicked(evt);
            }
        });
        jPanel2.add(lblregresarAlMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jPanel6.setBackground(new java.awt.Color(140, 0, 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 30));

        jLabel1.setText("EDITAR O AMPLIAR CUENTA");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 460, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/camareros-2958294[1].jpg"))); // NOI18N
        jLabel60.setText("jLabel60");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 320));

        jFrame2.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 480));

        jFrame3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("NUMERO DE ORDEN");
        jFrame3.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jFrame3.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jTable2.setBackground(new java.awt.Color(226, 196, 153));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2", "POLLO", "$5.00"},
                {"3", "CARNE ", "$5.00"},
                {"1", "AGUA", "$0.50"},
                {"3", "CUBA LIBRE", "$3.00"}
            },
            new String [] {
                "CANTIDAD", "PRODUCTO", "PRECIO"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jFrame3.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 150));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tarjeta-de-credito.png"))); // NOI18N
        jFrame3.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel21.setText("TOTAL");
        jFrame3.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        jLabel24.setText("$33.50");
        jFrame3.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        lblregresarAlMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/atras.png"))); // NOI18N
        lblregresarAlMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregresarAlMenu2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblregresarAlMenu2MouseMoved(evt);
            }
        });
        lblregresarAlMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregresarAlMenu2MouseClicked(evt);
            }
        });
        jFrame3.getContentPane().add(lblregresarAlMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jPanel10.setBackground(new java.awt.Color(140, 0, 4));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel66.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 30));

        jLabel8.setText("FINALIZAR ORDEN");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 160, -1));

        jFrame3.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        jPanel11.setBackground(new java.awt.Color(226, 196, 153));
        jFrame3.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 780, 400));

        jPanel5.setBackground(new java.awt.Color(226, 196, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setBackground(new java.awt.Color(226, 196, 153));
        jCheckBox1.setText("POR VENTAS ");
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(226, 196, 153));
        jCheckBox2.setText("ALFABETICO");
        jPanel5.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jButton3.setBackground(new java.awt.Color(226, 196, 153));
        jButton3.setText("ORDENAR");
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        jTable3.setBackground(new java.awt.Color(226, 196, 153));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"POLLO", "3", "$15.00"},
                {"CARNE", "4", "$20.00"},
                {"CUBA LIBRE", "5", null}
            },
            new String [] {
                "PRODUCTO", "VENTAS", "COSTO"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 110));

        jCheckBox3.setBackground(new java.awt.Color(226, 196, 153));
        jCheckBox3.setText("FECHA");
        jPanel5.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        lblregresarAlMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/atras.png"))); // NOI18N
        lblregresarAlMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregresarAlMenu3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblregresarAlMenu3MouseMoved(evt);
            }
        });
        lblregresarAlMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregresarAlMenu3MouseClicked(evt);
            }
        });
        jPanel5.add(lblregresarAlMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jPanel12.setBackground(new java.awt.Color(140, 0, 4));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel67.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel67MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel68.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel68MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 30));

        jLabel11.setText("estadisticas");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        jFrame4.getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreso.setBackground(new java.awt.Color(140, 0, 10));
        ingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ingreso.setForeground(new java.awt.Color(255, 255, 255));
        ingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        lblme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmeMouseClicked(evt);
            }
        });
        ingreso.add(lblme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTextField1.setBackground(new java.awt.Color(226, 196, 153));
        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(140, 0, 10));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Buscar");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        ingreso.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 480, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Search_32px_2.png"))); // NOI18N
        ingreso.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 40, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        ingreso.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        getContentPane().add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 50));

        MenuPrincipal.setBackground(new java.awt.Color(226, 196, 153));
        MenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblmenu.setBackground(new java.awt.Color(200, 0, 10));
        lblmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menu.png"))); // NOI18N
        lblmenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblmenuMouseMoved(evt);
            }
        });
        lblmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblmenuMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 180, 150));

        lblAmpliar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmpliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/notas.png"))); // NOI18N
        lblAmpliar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAmpliarMouseMoved(evt);
            }
        });
        lblAmpliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAmpliarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAmpliarMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblAmpliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 180, 150));

        lblFinalizaOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalizaOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/invoice.png"))); // NOI18N
        lblFinalizaOrden.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFinalizaOrdenMouseMoved(evt);
            }
        });
        lblFinalizaOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFinalizaOrdenMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFinalizaOrdenMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblFinalizaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 180, 150));

        lblAdministrarProductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministrarProductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/anillo.png"))); // NOI18N
        lblAdministrarProductor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAdministrarProductorMouseMoved(evt);
            }
        });
        lblAdministrarProductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdministrarProductorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdministrarProductorMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblAdministrarProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 180, 150));

        lblConcultarVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcultarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bars-chart.png"))); // NOI18N
        lblConcultarVentas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblConcultarVentasMouseMoved(evt);
            }
        });
        lblConcultarVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConcultarVentasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConcultarVentasMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblConcultarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 190, 150));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("Nueva Orden");
        jLabel12.setToolTipText("");
        MenuPrincipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 20));

        jLabel13.setBackground(new java.awt.Color(255, 99, 71));
        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Ampliar o Modificar Orden");
        jLabel13.setToolTipText("");
        MenuPrincipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 20));

        jLabel14.setBackground(new java.awt.Color(255, 99, 71));
        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 99, 71));
        jLabel14.setText("Finalizar Orden");
        jLabel14.setToolTipText("");
        MenuPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, 20));

        jLabel15.setBackground(new java.awt.Color(255, 99, 71));
        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setText("Administrar Productos");
        jLabel15.setToolTipText("");
        MenuPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, 20));

        jLabel16.setBackground(new java.awt.Color(255, 99, 71));
        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 99, 71));
        jLabel16.setText("Consultar Ventas");
        jLabel16.setToolTipText("");
        MenuPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, 20));

        lblcalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        lblcalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcalculadoraMouseClicked(evt);
            }
        });
        MenuPrincipal.add(lblcalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, -1, -1));

        getContentPane().add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 760, 500));

        ingreso1.setBackground(new java.awt.Color(232, 167, 53));
        ingreso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ingreso1.setForeground(new java.awt.Color(255, 255, 255));
        ingreso1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcalculadora1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        lblcalculadora1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcalculadora1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcalculadora1MouseClicked(evt);
            }
        });
        ingreso1.add(lblcalculadora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, -1, -1));

        getContentPane().add(ingreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmeMouseClicked
AnimationClass Calculadorai =new AnimationClass();     
AnimationClass Calculadorad =new AnimationClass();     
   
Calculadorad.jLabelXRight(-40, 0, 10, 5, lblcalculadora);

Calculadorai.jLabelXLeft(0, -40, 10, 5, lblcalculadora);

        
    }//GEN-LAST:event_lblmeMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
int dialog=JOptionPane.YES_NO_OPTION;
int resultado=JOptionPane.showConfirmDialog(null, "Desea salir","Exit",dialog);
if(resultado==0){
    System.exit(0);
}
    }//GEN-LAST:event_jLabel18MouseClicked

    private void lblmenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmenuMouseMoved
        lblmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblmenuMouseMoved

    private void lblmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmenuMouseExited
 lblmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblmenuMouseExited

    private void lblAmpliarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmpliarMouseMoved
 lblAmpliar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblAmpliarMouseMoved

    private void lblAmpliarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmpliarMouseExited
 lblAmpliar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblAmpliarMouseExited

    private void lblFinalizaOrdenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizaOrdenMouseMoved
 lblFinalizaOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblFinalizaOrdenMouseMoved

    private void lblAdministrarProductorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdministrarProductorMouseMoved
 lblAdministrarProductor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblAdministrarProductorMouseMoved

    private void lblConcultarVentasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConcultarVentasMouseMoved
 lblConcultarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblConcultarVentasMouseMoved

    private void lblFinalizaOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizaOrdenMouseExited
 lblFinalizaOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblFinalizaOrdenMouseExited

    private void lblAdministrarProductorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdministrarProductorMouseExited
 lblAdministrarProductor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblAdministrarProductorMouseExited

    private void lblConcultarVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConcultarVentasMouseExited
lblConcultarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));        // TODO add your handling code here:
    }//GEN-LAST:event_lblConcultarVentasMouseExited

    private void lblcalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcalculadoraMouseClicked
        try {
            Runtime cl = Runtime.getRuntime();
            Process p=cl.exec("calc");
            p.waitFor();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblcalculadoraMouseClicked

    private void lblmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmenuMouseClicked
//  MenuComida.setVisible(true);
//        MenuComida.setLocationRelativeTo(null);
//        this.dispose();
 jFrame1.setVisible(true);
    jFrame1.setLocationRelativeTo(null);
    jFrame1.setSize(1008, 564);
    jFrame1.setLocationRelativeTo(null);
    this.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_lblmenuMouseClicked

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
int dialog=JOptionPane.YES_NO_OPTION;
int resultado=JOptionPane.showConfirmDialog(null, "Desea salir","Exit",dialog);
if(resultado==0){
    System.exit(0);
    
}
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
AnimationClass Calculadorai =new AnimationClass();     
AnimationClass Calculadorad =new AnimationClass();     
   
Calculadorad.jLabelXRight(-40, 10, 10, 5, lblAdmin);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblAdmin);

Calculadorad.jLabelXRight(-40, 10, 10, 5, lblventas);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblventas);
Calculadorad.jLabelXRight(-40, 10, 10, 5, lblpagar);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblpagar);
Calculadorad.jLabelXRight(-40, 10, 10, 5, lblcambio);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblcambio);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lblcalculadora1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcalculadora1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcalculadora1MouseClicked

    private void lblAmpliarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmpliarMouseClicked
 jFrame2.setVisible(true);
    jFrame2.setLocationRelativeTo(null);
    jFrame2.setSize(636, 478);
    jFrame2.setLocationRelativeTo(null);
    this.setLocationRelativeTo(null);
    this.dispose();

    }//GEN-LAST:event_lblAmpliarMouseClicked

    private void lblRegresarPedidoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarPedidoMouseMoved
        lblRegresarPedido.setToolTipText("Rechazar elemento");
    }//GEN-LAST:event_lblRegresarPedidoMouseMoved

    private void lblagregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblagregarMouseMoved
        lblagregar.setToolTipText("Agregar a la orden ");
    }//GEN-LAST:event_lblagregarMouseMoved

    private void lblregresarAlMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenuMouseMoved
        lblregresarAlMenu.setToolTipText("Regresar al menu principal");
    }//GEN-LAST:event_lblregresarAlMenuMouseMoved

    private void lblregresarAlMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenuMouseClicked
        int dialog=JOptionPane.YES_NO_OPTION;
        int resultado=JOptionPane.showConfirmDialog(null, "DESEA REGRESAR AL MENU PRINCIPAL","EXIT",dialog);
        if(resultado==0){

            jFrame1.setVisible(false);
            this.setVisible(true);
        }
    }//GEN-LAST:event_lblregresarAlMenuMouseClicked

    private void lblregresarAlMenu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenu1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblregresarAlMenu1MouseMoved

    private void lblregresarAlMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenu1MouseClicked
int dialog=JOptionPane.YES_NO_OPTION;
        int resultado=JOptionPane.showConfirmDialog(null, "DESEA REGRESAR AL MENU PRINCIPAL","EXIT",dialog);
        if(resultado==0){

            jFrame2.setVisible(false);
            this.setVisible(true); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_lblregresarAlMenu1MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void lblregresarAlMenu2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenu2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblregresarAlMenu2MouseMoved

    private void lblregresarAlMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenu2MouseClicked
int dialog=JOptionPane.YES_NO_OPTION;
        int resultado=JOptionPane.showConfirmDialog(null, "DESEA REGRESAR AL MENU PRINCIPAL","EXIT",dialog);
        if(resultado==0){

            jFrame3.setVisible(false);
            this.setVisible(true); 
        }// TODO        // TODO add your handling code here:
    }//GEN-LAST:event_lblregresarAlMenu2MouseClicked

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel66MouseClicked

    private void lblregresarAlMenu3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenu3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblregresarAlMenu3MouseMoved

    private void lblregresarAlMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenu3MouseClicked
 int dialog=JOptionPane.YES_NO_OPTION;
        int resultado=JOptionPane.showConfirmDialog(null, "DESEA REGRESAR AL MENU PRINCIPAL","EXIT",dialog);
        if(resultado==0){

            jFrame4.setVisible(false);
            this.setVisible(true); 
        }// TOD
    }//GEN-LAST:event_lblregresarAlMenu3MouseClicked

    private void lblFinalizaOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizaOrdenMouseClicked
 jFrame3.setVisible(true);
    jFrame3.setLocationRelativeTo(null);
    jFrame3.setSize(778, 398);
    jFrame3.setLocationRelativeTo(null);
    this.setLocationRelativeTo(null);
    this.dispose();

    }//GEN-LAST:event_lblFinalizaOrdenMouseClicked

    private void lblAdministrarProductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdministrarProductorMouseClicked

    }//GEN-LAST:event_lblAdministrarProductorMouseClicked

    private void lblConcultarVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConcultarVentasMouseClicked
    jFrame4.setVisible(true);
    jFrame4.setLocationRelativeTo(null);
    jFrame4.setSize(776,363);
    jFrame4.setLocationRelativeTo(null);
    this.setLocationRelativeTo(null);
    this.dispose();

    }//GEN-LAST:event_lblConcultarVentasMouseClicked

    private void jLabel67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel67MouseClicked

    private void jLabel68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel68MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel ingreso;
    private javax.swing.JPanel ingreso1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner17;
    private javax.swing.JSpinner jSpinner18;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdministrarProductor;
    private javax.swing.JLabel lblAmpliar;
    private javax.swing.JLabel lblConcultarVentas;
    private javax.swing.JLabel lblFinalizaOrden;
    private javax.swing.JLabel lblRegresarPedido;
    private javax.swing.JLabel lblagregar;
    private javax.swing.JLabel lblcalculadora;
    private javax.swing.JLabel lblcalculadora1;
    private javax.swing.JLabel lblcambio;
    private javax.swing.JLabel lblme;
    private javax.swing.JLabel lblmenu;
    private javax.swing.JLabel lblpagar;
    private javax.swing.JLabel lblregresarAlMenu;
    private javax.swing.JLabel lblregresarAlMenu1;
    private javax.swing.JLabel lblregresarAlMenu2;
    private javax.swing.JLabel lblregresarAlMenu3;
    private javax.swing.JLabel lblventas;
    // End of variables declaration//GEN-END:variables
}
