/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author omar1
 */
import AppPackage.AnimationClass;
import javax.swing.JOptionPane;
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();   
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel59 = new javax.swing.JLabel();
        lblagregar = new javax.swing.JLabel();
        lblregresarAlMenu = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblcambio = new javax.swing.JLabel();
        lblventas = new javax.swing.JLabel();
        lblpagar = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblRegresarPedido = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jSpinner15 = new javax.swing.JSpinner();
        jSpinner16 = new javax.swing.JSpinner();
        jSpinner17 = new javax.swing.JSpinner();
        jSpinner18 = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jFrame2 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jOptionPane1 = new javax.swing.JOptionPane();
        ingreso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblme = new javax.swing.JLabel();
        lblcalculadora = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JPanel();
        lblsalir = new javax.swing.JLabel();
        lblmenu = new javax.swing.JLabel();
        lblAmpliar = new javax.swing.JLabel();
        lblFinalizaOrden = new javax.swing.JLabel();
        lblAdministrarProductor = new javax.swing.JLabel();
        lblConcultarVentas = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        jFrame1.setUndecorated(true);
        jFrame1.setResizable(false);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "2xCARNE   $5.00", "3xCUBA LIBRE $3.00", "2xGELATINAS  $1.00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, 210));

        jLabel59.setText("ORDEN ACTUAL");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lblagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anadir-mas-naranja-icono-6506-128 (64 x 64).jpg"))); // NOI18N
        lblagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblagregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblagregarMouseMoved(evt);
            }
        });
        jPanel1.add(lblagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        lblregresarAlMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3f87a7cc00730e71d0234072f99af2dc (64 x 64).jpg"))); // NOI18N
        lblregresarAlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregresarAlMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblregresarAlMenuMouseMoved(evt);
            }
        });
        lblregresarAlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregresarAlMenuMouseClicked(evt);
            }
        });
        jPanel1.add(lblregresarAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel64.setText("TOTAL :");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel65.setText("$21.00");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anillo (32 x 32).jpg"))); // NOI18N
        lblAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, -1, -1));

        lblcambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/notas (32 x 32).jpg"))); // NOI18N
        lblcambio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblcambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, -1, -1));

        lblventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bars-chart (32 x 32).jpg"))); // NOI18N
        lblventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 200, -1, -1));

        lblpagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/invoice (32 x 32).jpg"))); // NOI18N
        lblpagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 160, -1, -1));

        jLabel22.setText("NUMERO DE ORDEN :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel23.setText("1");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        lblRegresarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Return (64 x 64).jpg"))); // NOI18N
        lblRegresarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegresarPedido.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRegresarPedidoMouseMoved(evt);
            }
        });
        jPanel1.add(lblRegresarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 60, -1));

        jFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 40, 30));

        jFrame1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 40));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cortesdecarne (150 x 113).png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 100));

        jLabel5.setText("PLATO DE CARNE $5.00");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 20));
        jPanel7.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 50, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pOpera.jpg"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 120));
        jPanel7.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 50, -1));

        jLabel10.setText("PURE DE PAPA $3.00");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pSiciliana.jpg"))); // NOI18N
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));
        jPanel7.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 50, -1));

        jLabel28.setText("LASAÑA  $5.00");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/images2 (150 x 113).jpg"))); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel30.setText("SOPA  $3.00");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 20));
        jPanel7.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 50, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/0343-bocata-de-pollo-asado-con-guacamole-xl-416x236x80xX (150 x 113).jpg"))); // NOI18N
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/85e1595251e8d58308db168e689a0f28db17f9eb_r900_480_2 (150 x 113).jpg"))); // NOI18N
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel33.setText("SANDWICH $4.00");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, 20));

        jLabel34.setText("POLLA    $5.00");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, 20));
        jPanel7.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 40, -1));
        jPanel7.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 50, -1));

        jTabbedPane1.addTab("COMIDA", new javax.swing.ImageIcon(getClass().getResource("/Img/cubiertos (32 x 32).jpg")), jPanel7); // NOI18N

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/10postresconlechecondensada (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gelatina-de-navidad (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/images (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/images4 (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/istock89179523small (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/soyfler- (150 x 113).jpg"))); // NOI18N
        jPanel9.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel53.setText("VOLCAN DE CHOCOLATE $3.00");
        jPanel9.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 130, 20));

        jLabel54.setText("PIE DE LIMON $2.00");
        jPanel9.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 20));

        jLabel55.setText("GELATINAS  $1.00");
        jPanel9.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 90, 20));

        jLabel56.setText("PASTEL DE CHOCOLATE $2.00");
        jPanel9.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 160, 20));

        jLabel57.setText("PIE DE FRUTAS $2.50");
        jPanel9.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 110, 20));

        jLabel58.setText("FLAN DE FRESAS $1.00");
        jPanel9.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 120, 20));
        jPanel9.add(jSpinner13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 50, -1));
        jPanel9.add(jSpinner14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 50, -1));
        jPanel9.add(jSpinner15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 50, -1));
        jPanel9.add(jSpinner16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 50, -1));
        jPanel9.add(jSpinner17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 50, -1));
        jPanel9.add(jSpinner18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 50, -1));

        jTabbedPane1.addTab("POSTRES", new javax.swing.ImageIcon(getClass().getResource("/Img/depositphotos_140707304-stock-illustration-chocolate-ice-cream-icon-in (32 x 32).jpg")), jPanel9); // NOI18N

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agua_opt.png"))); // NOI18N
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 110));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/index (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cafe (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cafe(150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dt.common.streams.StreamServer.cls (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mandarina---naranja (150 x 113).jpg"))); // NOI18N
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jLabel41.setText("AGUA  $0.25");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        jLabel42.setText("CEBEZA  $2.00");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 20));

        jLabel43.setText("CAPICHINO  $1.50");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 20));

        jLabel44.setText("CAFE  $1.00");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 20));

        jLabel45.setText("CUBA LIBRE  $3.00");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, 20));

        jLabel46.setText("JUGO  $1.50");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, 20));
        jPanel8.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 40, -1));
        jPanel8.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 190, 40, -1));
        jPanel8.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 40, -1));
        jPanel8.add(jSpinner10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 40, -1));
        jPanel8.add(jSpinner11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 40, -1));
        jPanel8.add(jSpinner12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 40, -1));

        jTabbedPane1.addTab("BEBIDA", new javax.swing.ImageIcon(getClass().getResource("/Img/images (32 x 32).jpg")), jPanel8); // NOI18N

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 530));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Comida");

        jFrame1.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 760, 530));

        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jFrame2.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1, 480));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreso.setBackground(new java.awt.Color(255, 255, 255));
        ingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ingreso.setForeground(new java.awt.Color(255, 255, 255));
        ingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_User_96px_2.png"))); // NOI18N
        ingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 80));

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("RESBAR");
        ingreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, 60));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("Bienvenido ");
        ingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 60));

        lblme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        lblme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmeMouseClicked(evt);
            }
        });
        ingreso.add(lblme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblcalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        lblcalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcalculadoraMouseClicked(evt);
            }
        });
        ingreso.add(lblcalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, -1, -1));

        getContentPane().add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        MenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        MenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/desconexion-de-salida-icono-7025-128_1.png"))); // NOI18N
        lblsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblsalirMouseMoved(evt);
            }
        });
        lblsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsalirMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 180, 150));

        lblmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menu.png"))); // NOI18N
        lblmenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblmenuMouseMoved(evt);
            }
        });
        lblmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblmenuMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, 150));

        lblAmpliar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmpliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/notas.png"))); // NOI18N
        lblAmpliar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAmpliarMouseMoved(evt);
            }
        });
        lblAmpliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAmpliarMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblAmpliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 180, 150));

        lblFinalizaOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalizaOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/invoice.png"))); // NOI18N
        lblFinalizaOrden.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFinalizaOrdenMouseMoved(evt);
            }
        });
        lblFinalizaOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFinalizaOrdenMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblFinalizaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 180, 150));

        lblAdministrarProductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministrarProductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/anillo.png"))); // NOI18N
        lblAdministrarProductor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAdministrarProductorMouseMoved(evt);
            }
        });
        lblAdministrarProductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdministrarProductorMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblAdministrarProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 150));

        lblConcultarVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcultarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bars-chart.png"))); // NOI18N
        lblConcultarVentas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblConcultarVentasMouseMoved(evt);
            }
        });
        lblConcultarVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConcultarVentasMouseExited(evt);
            }
        });
        MenuPrincipal.add(lblConcultarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 190, 150));

        jLabel11.setBackground(new java.awt.Color(255, 99, 71));
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setText("Salir");
        jLabel11.setToolTipText("");
        MenuPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, 20));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("Nueva Orden");
        jLabel12.setToolTipText("");
        MenuPrincipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 20));

        jLabel13.setBackground(new java.awt.Color(255, 99, 71));
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Ampliar o Modificar Orden");
        jLabel13.setToolTipText("");
        MenuPrincipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 20));

        jLabel14.setBackground(new java.awt.Color(255, 99, 71));
        jLabel14.setForeground(new java.awt.Color(255, 99, 71));
        jLabel14.setText("Finalizar Orden");
        jLabel14.setToolTipText("");
        MenuPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, 20));

        jLabel15.setBackground(new java.awt.Color(255, 99, 71));
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setText("Administrar Productos");
        jLabel15.setToolTipText("");
        MenuPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 20));

        jLabel16.setBackground(new java.awt.Color(255, 99, 71));
        jLabel16.setForeground(new java.awt.Color(255, 99, 71));
        jLabel16.setText("Concultar Ventas");
        jLabel16.setToolTipText("");
        MenuPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, 20));

        jTextField1.setFont(new java.awt.Font("Vivaldi", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Buscar");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        MenuPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 170, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Search_32px_2.png"))); // NOI18N
        MenuPrincipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 40, 30));

        getContentPane().add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 760, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmeMouseClicked
AnimationClass Calculadorai =new AnimationClass();     
AnimationClass Calculadorad =new AnimationClass();     
   
Calculadorad.jLabelXRight(-40, 10, 10, 5, lblcalculadora);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblcalculadora);

        
    }//GEN-LAST:event_lblmeMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
int dialog=JOptionPane.YES_NO_OPTION;
int resultado=JOptionPane.showConfirmDialog(null, "Desea salir","Exit",dialog);
if(resultado==0){
    System.exit(0);
}
    }//GEN-LAST:event_jLabel18MouseClicked

    private void lblmenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmenuMouseMoved
        lblmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblmenuMouseMoved

    private void lblmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmenuMouseExited
 lblmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblmenuMouseExited

    private void lblAmpliarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmpliarMouseMoved
 lblAmpliar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblAmpliarMouseMoved

    private void lblAmpliarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmpliarMouseExited
 lblAmpliar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblAmpliarMouseExited

    private void lblFinalizaOrdenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizaOrdenMouseMoved
 lblFinalizaOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblFinalizaOrdenMouseMoved

    private void lblAdministrarProductorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdministrarProductorMouseMoved
 lblAdministrarProductor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblAdministrarProductorMouseMoved

    private void lblConcultarVentasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConcultarVentasMouseMoved
 lblConcultarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblConcultarVentasMouseMoved

    private void lblsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalirMouseMoved
 lblsalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblsalirMouseMoved

    private void lblFinalizaOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizaOrdenMouseExited
 lblFinalizaOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblFinalizaOrdenMouseExited

    private void lblAdministrarProductorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdministrarProductorMouseExited
 lblAdministrarProductor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblAdministrarProductorMouseExited

    private void lblConcultarVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConcultarVentasMouseExited
lblConcultarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));        // TODO add your handling code here:
    }//GEN-LAST:event_lblConcultarVentasMouseExited

    private void lblsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalirMouseExited
lblsalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblsalirMouseExited

    private void lblcalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcalculadoraMouseClicked
        try {
            Runtime cl = Runtime.getRuntime();
            Process p=cl.exec("calc");
            p.waitFor();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblcalculadoraMouseClicked

    private void lblmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmenuMouseClicked
//  MenuComida.setVisible(true);
//        MenuComida.setLocationRelativeTo(null);
//        this.dispose();
    jFrame1.setVisible(true);
    jFrame1.setLocationRelativeTo(null);
    jFrame1.setSize(1050, 575);
    jFrame1.setLocationRelativeTo(null);
    this.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_lblmenuMouseClicked

    private void lblagregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblagregarMouseMoved
lblagregar.setToolTipText("Agregar a la orden ");
    }//GEN-LAST:event_lblagregarMouseMoved

    private void lblregresarAlMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenuMouseMoved
lblregresarAlMenu.setToolTipText("Regresar al menu principal");
    }//GEN-LAST:event_lblregresarAlMenuMouseMoved

    private void lblRegresarPedidoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarPedidoMouseMoved
lblRegresarPedido.setToolTipText("Rechazar elemento");
    }//GEN-LAST:event_lblRegresarPedidoMouseMoved

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
int dialog=JOptionPane.YES_NO_OPTION;
int resultado=JOptionPane.showConfirmDialog(null, "Desea salir","Exit",dialog);
if(resultado==0){
    System.exit(0);
    
}
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
AnimationClass Calculadorai =new AnimationClass();     
AnimationClass Calculadorad =new AnimationClass();     
   
Calculadorad.jLabelXRight(-40, 10, 10, 5, lblAdmin);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblAdmin);

Calculadorad.jLabelXRight(-40, 10, 10, 5, lblventas);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblventas);
Calculadorad.jLabelXRight(-40, 10, 10, 5, lblpagar);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblpagar);
Calculadorad.jLabelXRight(-40, 10, 10, 5, lblcambio);

Calculadorai.jLabelXLeft(10, -40, 10, 5, lblcambio);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void lblregresarAlMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarAlMenuMouseClicked
int dialog=JOptionPane.YES_NO_OPTION;
int resultado=JOptionPane.showConfirmDialog(null, "DESEA REGRESAR AL MENU PRINCIPAL","EXIT",dialog);
if(resultado==0){

        jFrame1.setVisible(false);
        this.setVisible(true);
}
    }//GEN-LAST:event_lblregresarAlMenuMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel ingreso;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner17;
    private javax.swing.JSpinner jSpinner18;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdministrarProductor;
    private javax.swing.JLabel lblAmpliar;
    private javax.swing.JLabel lblConcultarVentas;
    private javax.swing.JLabel lblFinalizaOrden;
    private javax.swing.JLabel lblRegresarPedido;
    private javax.swing.JLabel lblagregar;
    private javax.swing.JLabel lblcalculadora;
    private javax.swing.JLabel lblcambio;
    private javax.swing.JLabel lblme;
    private javax.swing.JLabel lblmenu;
    private javax.swing.JLabel lblpagar;
    private javax.swing.JLabel lblregresarAlMenu;
    private javax.swing.JLabel lblsalir;
    private javax.swing.JLabel lblventas;
    // End of variables declaration//GEN-END:variables
}
